-- migrate:up

#입주 기업
INSERT INTO user_group (company_name, start_date, end_date) VALUES ('justcode', '1900-01-01', '2100-12-31');
INSERT INTO user_group (company_name, start_date, end_date) VALUES ('둘레 에이아이', '1900-01-01', '2100-12-31');
INSERT INTO user_group (company_name, start_date, end_date) VALUES ('순양 개발', '2022-01-01', '2023-12-31');
INSERT INTO user_group (company_name, start_date, end_date) VALUES ('대영 솔루션', '2022-01-01', '2023-12-31');
INSERT INTO user_group (company_name, start_date, end_date) VALUES ('QA의 모든 것', '2022-01-01', '2023-12-31');
INSERT INTO user_group (company_name, start_date, end_date) VALUES ('DG & TY', '2022-12-23', '2023-12-31');
INSERT INTO user_group (company_name, start_date, end_date) VALUES ('SHIELD', '2021-01-01', '2023-12-31');
#입주예정 기업
INSERT INTO user_group (company_name, start_date, end_date) VALUES ('세탁 상태', '2023-03-01', '2023-12-31');
#퇴주 기업
INSERT INTO user_group (company_name, start_date, end_date) VALUES ('트러스트인', '2022-01-01', '2021-12-31');
#일반가입 기업
INSERT INTO user_group (company_name) VALUES ('VScode');

# 닉네임이 곧 패스워드입니다. API 테스트시 사용하시면 됩니다.
#개발자
INSERT INTO users (nickname, password, email, position_name,is_admin, group_id) VALUES ('admin1', '$2a$10$vQO3CQlKE5Bto7G1/nDvYurjnuiNBq3TXDrba54fr9iYhe.6Ej0K6', 'admin1@admin.com', '팀장', TRUE, 1);
#입주자
INSERT INTO users (nickname, password, email, position_name, is_admin, group_id) VALUES ('member1', '$2a$10$0rczKmnyiMChg5Kpm3y3y.fBrE2g4Fz8rEiRK4EgC3DBvQcvg98xG', 'member1@test.com', '대표',TRUE, 2);
INSERT INTO users (nickname, password, email, position_name, is_admin, group_id) VALUES ('member2', '$2a$10$7yp6C9VP2eMmHxryce1CIeTtpMrn4OGgCdsTx1bUlIfxSytU6ywlO', 'member2@test.com', '과장', TRUE,3);
INSERT INTO users (nickname, password, email, position_name, is_admin, group_id) VALUES ('member3', '$2a$10$w0aaQhzk8OPE9udI5nWTmumQ5gqVNids6vEdKeTkos50jpA7T5MD2', 'member3@test.com', '대리', TRUE, 4);
INSERT INTO users (nickname, password, email, position_name, is_admin, group_id) VALUES ('member4', '$2a$10$HnYarW5RUCdMRQJzb.bWguMwL9G9yR5kUc82jifCEQhZZSl/5Fk4K', 'member4@test.com', '주임', FALSE, 4);
INSERT INTO users (nickname, password, email, position_name, is_admin, group_id) VALUES ('member5', '$2a$10$HnYarW5RUCdMRQJzb.bWguMwL9G9yR5kUc82jifCEQhZZSl/5Fk4K', 'member5@test.com', '사원', TRUE, 5);
INSERT INTO users (nickname, password, email, position_name, is_admin, group_id) VALUES ('member6', '$2a$10$lFhp6q4c0XKKN2cwR4E04OOeaV3uiFhK7V3WFO8kuPWzn.LbVOtXu', 'member6@test.com', '과장', TRUE, 6);
INSERT INTO users (nickname, password, email, position_name, is_admin, group_id) VALUES ('member7', '$2a$10$eVDJVpLgotjdGb/ETCQjFeSV5R4g9.b/LpziylGixAmcpI0e9Zo8q', 'member7@test.com', '차장', TRUE, 7);
# INSERT INTO users (nickname, password, email, position_name, is_admin, group_id) VALUES ('member8', '$2a$10$UiZdG8o6o9HdlV6vh66oxOHHkXtyUPgI6IJwxak5WW5gxiSVutuNi', 'member8@test.com', '주임', TRUE, 8);
# INSERT INTO users (nickname, password, email, position_name, is_admin, group_id) VALUES ('member9', '$2a$10$NUTKoskV5cHCM5GjfRhsp.OodYD3m9Jx.Z6Ljy7NPpLQyw5EOzjzG', 'member9@test.com', '대표', TRUE, 9);
#입주예정자
INSERT INTO users (nickname, password, email, position_name, is_admin, group_id) VALUES ('reservation1', '$2a$10$DWZwICvLDyeareRSbspZxurgiUydNxXAZ4eKueHUofWnFM6xKidve', 'reservation1@test.com', '대표', TRUE,8);
#퇴주자
INSERT INTO users (nickname, password, email, position_name, is_admin, group_id) VALUES ('member6exit', '$2a$10$BIFBNVZ2p2Zk0wL1ueQEBu7wGvtfVYfK5DLkEyXPBHFm6iOaoFMPG', 'member6exit@test.com', '사원',TRUE, 9);
#일반가입자
INSERT INTO users (nickname, password, email, position_name, is_admin, group_id) VALUES ('normal1', '$2a$10$HSnJV56pEEaT8C7hniwL/eb5j7vKtrjEyOghXJS2fMA0LHbRBOOU.', 'normal1@test.com', '대표', TRUE, 10);

# dummy company data
insert into user_group (company_name, start_date, end_date) values ('Twinte4291', '2022-01-14', '2024-04-21');
insert into user_group (company_name, start_date, end_date) values ('Dablist2540', '2022-04-15', '2024-03-20');
insert into user_group (company_name, start_date, end_date) values ('Dynabox3669', '2022-07-25', '2024-03-27');
insert into user_group (company_name, start_date, end_date) values ('Jetpulse6186', '2022-04-20', '2024-12-17');
insert into user_group (company_name, start_date, end_date) values ('Devbug9935', '2022-03-23', '2024-12-03');
insert into user_group (company_name, start_date, end_date) values ('Trupe3304', '2022-03-31', '2024-09-25');
insert into user_group (company_name, start_date, end_date) values ('Topiczoom5978', '2022-09-14', '2024-11-01');
insert into user_group (company_name, start_date, end_date) values ('Chatterpoint6159', '2022-07-10', '2024-01-14');
insert into user_group (company_name, start_date, end_date) values ('Brightdog7290', '2022-08-20', '2024-03-21');
insert into user_group (company_name, start_date, end_date) values ('Jaloo1852', '2022-10-25', '2024-03-20');
insert into user_group (company_name, start_date, end_date) values ('Abatz5314', '2021-06-16', '2024-09-01');
insert into user_group (company_name, start_date, end_date) values ('Twitterbridge7348', '2022-02-22', '2024-03-23');
insert into user_group (company_name, start_date, end_date) values ('Brightdog8684', '2022-04-26', '2024-06-07');
insert into user_group (company_name, start_date, end_date) values ('Dabvine9272', '2022-11-22', '2024-07-21');
insert into user_group (company_name, start_date, end_date) values ('Tagtune6942', '2022-10-14', '2024-12-10');
insert into user_group (company_name, start_date, end_date) values ('Kimia3556', '2021-06-21', '2024-02-06');
insert into user_group (company_name, start_date, end_date) values ('Aivee4032', '2021-08-29', '2024-09-12');
insert into user_group (company_name, start_date, end_date) values ('Bubblemix8493', '2022-04-13', '2024-07-17');
insert into user_group (company_name, start_date, end_date) values ('Roomm1573', '2022-08-05', '2024-09-12');
insert into user_group (company_name, start_date, end_date) values ('Tekfly3233', '2021-07-10', '2024-10-04');
insert into user_group (company_name, start_date, end_date) values ('Gabtype9634', '2021-06-27', '2024-10-13');
insert into user_group (company_name, start_date, end_date) values ('Topicware8044', '2021-06-19', '2024-10-03');
insert into user_group (company_name, start_date, end_date) values ('Buzzster1794', '2022-09-15', '2024-04-14');
insert into user_group (company_name, start_date, end_date) values ('Mybuzz7892', '2022-12-16', '2024-01-06');
insert into user_group (company_name, start_date, end_date) values ('Tagopia3033', '2021-09-13', '2024-07-21');
insert into user_group (company_name, start_date, end_date) values ('Jetwire5709', '2022-04-22', '2024-07-01');
insert into user_group (company_name, start_date, end_date) values ('Divavu3626', '2022-05-23', '2024-06-08');
insert into user_group (company_name, start_date, end_date) values ('Realcube4478', '2022-12-30', '2024-05-02');
insert into user_group (company_name, start_date, end_date) values ('Mydeo301', '2022-12-01', '2024-06-22');
insert into user_group (company_name, start_date, end_date) values ('Browsetype487', '2022-01-08', '2024-11-23');
insert into user_group (company_name, start_date, end_date) values ('Divanoodle5400', '2021-10-05', '2024-08-23');
insert into user_group (company_name, start_date, end_date) values ('Voomm3916', '2021-10-13', '2024-03-18');
insert into user_group (company_name, start_date, end_date) values ('Centidel2482', '2022-03-16', '2024-04-01');
insert into user_group (company_name, start_date, end_date) values ('Vidoo3660', '2021-05-03', '2024-09-10');
insert into user_group (company_name, start_date, end_date) values ('Kamba2603', '2022-10-13', '2024-06-24');
insert into user_group (company_name, start_date, end_date) values ('Meevee3830', '2021-09-21', '2024-12-17');
insert into user_group (company_name, start_date, end_date) values ('Innotype6075', '2022-05-07', '2024-09-12');
insert into user_group (company_name, start_date, end_date) values ('Fivebridge5161', '2022-07-22', '2024-08-22');
insert into user_group (company_name, start_date, end_date) values ('Skyvu8356', '2022-11-21', '2024-05-15');
insert into user_group (company_name, start_date, end_date) values ('Mynte4410', '2022-02-03', '2024-03-21');
insert into user_group (company_name, start_date, end_date) values ('Skimia2360', '2022-01-18', '2024-12-05');
insert into user_group (company_name, start_date, end_date) values ('Skidoo7432', '2022-08-19', '2024-03-12');
insert into user_group (company_name, start_date, end_date) values ('Abata3530', '2021-10-06', '2024-06-26');
insert into user_group (company_name, start_date, end_date) values ('Vimbo9456', '2021-08-04', '2024-03-05');
insert into user_group (company_name, start_date, end_date) values ('Yombu587', '2021-05-17', '2024-03-31');
insert into user_group (company_name, start_date, end_date) values ('Yodel344', '2022-10-22', '2024-02-26');
insert into user_group (company_name, start_date, end_date) values ('Katz421', '2021-10-18', '2024-07-01');
insert into user_group (company_name, start_date, end_date) values ('Photobean8196', '2021-12-30', '2024-06-04');
insert into user_group (company_name, start_date, end_date) values ('Wikizz4762', '2022-03-07', '2024-12-06');
insert into user_group (company_name, start_date, end_date) values ('Topiczoom7976', '2022-02-15', '2024-01-05');
insert into user_group (company_name, start_date, end_date) values ('Kanoodle6787', '2022-03-17', '2024-03-14');
insert into user_group (company_name, start_date, end_date) values ('Tagpad3387', '2022-04-27', '2024-05-10');
insert into user_group (company_name, start_date, end_date) values ('Zoomlounge5025', '2021-05-03', '2024-10-08');
insert into user_group (company_name, start_date, end_date) values ('Dazzlesphere6133', '2022-03-12', '2024-09-22');
insert into user_group (company_name, start_date, end_date) values ('Realfire8158', '2022-12-22', '2024-12-09');
insert into user_group (company_name, start_date, end_date) values ('Thoughtmix6783', '2022-08-22', '2024-11-29');
insert into user_group (company_name, start_date, end_date) values ('Shufflester5009', '2021-11-13', '2024-08-14');
insert into user_group (company_name, start_date, end_date) values ('Kaymbo3143', '2021-10-21', '2024-07-04');
insert into user_group (company_name, start_date, end_date) values ('Tagchat8995', '2021-12-08', '2024-08-19');
insert into user_group (company_name, start_date, end_date) values ('Shuffletag5436', '2021-05-04', '2024-06-30');
insert into user_group (company_name, start_date, end_date) values ('Fiveclub1442', '2021-06-01', '2024-04-26');
insert into user_group (company_name, start_date, end_date) values ('Realbuzz158', '2022-03-16', '2024-02-05');
insert into user_group (company_name, start_date, end_date) values ('Dazzlesphere8956', '2022-08-01', '2024-09-06');
insert into user_group (company_name, start_date, end_date) values ('Yoveo4145', '2021-11-10', '2024-11-09');
insert into user_group (company_name, start_date, end_date) values ('Skyvu2337', '2021-07-05', '2024-07-01');
insert into user_group (company_name, start_date, end_date) values ('Gigaclub2053', '2021-08-17', '2024-05-28');
insert into user_group (company_name, start_date, end_date) values ('Pixope9036', '2021-06-21', '2024-11-02');
insert into user_group (company_name, start_date, end_date) values ('Oyoloo1442', '2022-01-06', '2024-09-28');
insert into user_group (company_name, start_date, end_date) values ('Centizu5944', '2021-07-21', '2024-10-09');
insert into user_group (company_name, start_date, end_date) values ('Skivee8282', '2022-04-22', '2024-12-17');
insert into user_group (company_name, start_date, end_date) values ('Snaptags6947', '2022-09-04', '2024-06-28');
insert into user_group (company_name, start_date, end_date) values ('Feedfish8254', '2021-11-16', '2024-04-21');
insert into user_group (company_name, start_date, end_date) values ('Youopia3784', '2021-05-12', '2024-04-05');
insert into user_group (company_name, start_date, end_date) values ('Dynabox6523', '2022-11-17', '2024-12-25');
insert into user_group (company_name, start_date, end_date) values ('Jaxspan6360', '2021-08-17', '2024-11-05');
insert into user_group (company_name, start_date, end_date) values ('Demizz7287', '2022-02-21', '2024-03-21');
insert into user_group (company_name, start_date, end_date) values ('Plambee75', '2021-05-31', '2024-07-30');
insert into user_group (company_name, start_date, end_date) values ('Roomm9233', '2021-06-13', '2024-05-24');
insert into user_group (company_name, start_date, end_date) values ('Meeveo3469', '2021-08-07', '2024-02-14');
insert into user_group (company_name, start_date, end_date) values ('Quatz3716', '2021-08-05', '2024-06-23');
insert into user_group (company_name, start_date, end_date) values ('Devify4830', '2022-10-06', '2024-01-13');
insert into user_group (company_name, start_date, end_date) values ('Tagcat4634', '2022-10-23', '2024-03-06');
insert into user_group (company_name, start_date, end_date) values ('Zoomdog9827', '2021-11-27', '2024-10-11');
insert into user_group (company_name, start_date, end_date) values ('Twitterlist7824', '2022-05-26', '2024-12-01');
insert into user_group (company_name, start_date, end_date) values ('Podcat681', '2021-12-02', '2024-04-01');
insert into user_group (company_name, start_date, end_date) values ('Gigaclub2501', '2022-02-07', '2024-07-19');
insert into user_group (company_name, start_date, end_date) values ('Realbuzz4745', '2022-02-09', '2024-07-18');
insert into user_group (company_name, start_date, end_date) values ('Ooba310', '2021-10-16', '2024-01-14');
insert into user_group (company_name, start_date, end_date) values ('Brainsphere3940', '2021-12-28', '2024-01-31');
insert into user_group (company_name, start_date, end_date) values ('Zava9669', '2022-02-04', '2024-04-17');
insert into user_group (company_name, start_date, end_date) values ('Shufflester2419', '2022-12-24', '2024-06-08');
insert into user_group (company_name, start_date, end_date) values ('BlogXS7279', '2022-05-02', '2024-10-16');
insert into user_group (company_name, start_date, end_date) values ('Feedspan9181', '2022-10-26', '2024-11-23');
insert into user_group (company_name, start_date, end_date) values ('LiveZ3256', '2021-07-02', '2024-12-20');
insert into user_group (company_name, start_date, end_date) values ('Realpoint8668', '2022-10-05', '2024-01-18');
insert into user_group (company_name, start_date, end_date) values ('Wikizz5659', '2021-08-10', '2024-12-22');
insert into user_group (company_name, start_date, end_date) values ('Photospace8874', '2022-03-28', '2024-07-24');
insert into user_group (company_name, start_date, end_date) values ('Gevee2951', '2022-04-14', '2024-04-09');
insert into user_group (company_name, start_date, end_date) values ('Meemm7828', '2021-10-10', '2024-08-01');
insert into user_group (company_name, start_date, end_date) values ('Trilith2313', '2021-08-02', '2024-09-26');
insert into user_group (company_name, start_date, end_date) values ('Aimbu3145', '2022-09-06', '2024-11-14');
insert into user_group (company_name, start_date, end_date) values ('Leexo5922', '2021-07-17', '2024-05-31');
insert into user_group (company_name, start_date, end_date) values ('JumpXS6637', '2022-05-28', '2024-08-20');
insert into user_group (company_name, start_date, end_date) values ('Twimbo1850', '2022-11-28', '2024-04-17');
insert into user_group (company_name, start_date, end_date) values ('Mybuzz3599', '2022-04-28', '2024-01-22');
insert into user_group (company_name, start_date, end_date) values ('Meetz435', '2022-12-12', '2024-11-13');
insert into user_group (company_name, start_date, end_date) values ('Zoomcast7669', '2022-08-07', '2024-08-15');
insert into user_group (company_name, start_date, end_date) values ('Yakijo7841', '2022-09-11', '2024-12-23');
insert into user_group (company_name, start_date, end_date) values ('Oyoba6741', '2022-08-19', '2024-04-19');
insert into user_group (company_name, start_date, end_date) values ('Photobean9486', '2022-10-02', '2024-07-17');
insert into user_group (company_name, start_date, end_date) values ('Quatz2771', '2022-07-29', '2024-03-20');
insert into user_group (company_name, start_date, end_date) values ('Photobug7294', '2022-04-28', '2024-09-07');
insert into user_group (company_name, start_date, end_date) values ('Centizu5889', '2022-07-04', '2024-05-22');
insert into user_group (company_name, start_date, end_date) values ('Flashdog5511', '2021-06-01', '2024-09-10');
insert into user_group (company_name, start_date, end_date) values ('Bluezoom7259', '2021-08-12', '2024-07-28');
insert into user_group (company_name, start_date, end_date) values ('Meembee4422', '2022-01-29', '2024-06-11');
insert into user_group (company_name, start_date, end_date) values ('Minyx4683', '2022-04-22', '2024-11-14');
insert into user_group (company_name, start_date, end_date) values ('Zoombox8434', '2021-10-20', '2024-09-14');
insert into user_group (company_name, start_date, end_date) values ('Skajo2333', '2022-01-01', '2024-03-26');
insert into user_group (company_name, start_date, end_date) values ('Digitube609', '2022-07-31', '2024-11-02');
insert into user_group (company_name, start_date, end_date) values ('DabZ1128', '2023-01-11', '2024-09-20');
insert into user_group (company_name, start_date, end_date) values ('Youspan5963', '2022-03-08', '2024-08-31');
insert into user_group (company_name, start_date, end_date) values ('Browsetype8240', '2022-10-17', '2024-07-04');
insert into user_group (company_name, start_date, end_date) values ('Photobug7640', '2021-06-03', '2024-08-02');
insert into user_group (company_name, start_date, end_date) values ('Dabshots2138', '2022-06-30', '2024-06-10');
insert into user_group (company_name, start_date, end_date) values ('Camimbo2290', '2022-03-19', '2024-09-09');
insert into user_group (company_name, start_date, end_date) values ('Skivee8508', '2022-12-06', '2024-03-18');
insert into user_group (company_name, start_date, end_date) values ('Dynabox1898', '2021-12-03', '2024-02-20');
insert into user_group (company_name, start_date, end_date) values ('Feedmix6785', '2021-11-24', '2024-05-10');
insert into user_group (company_name, start_date, end_date) values ('Twimbo9722', '2022-02-27', '2024-05-11');
insert into user_group (company_name, start_date, end_date) values ('Thoughtsphere8841', '2022-07-08', '2024-07-14');
insert into user_group (company_name, start_date, end_date) values ('Aimbo669', '2022-11-01', '2024-09-05');
insert into user_group (company_name, start_date, end_date) values ('Chatterpoint8900', '2021-06-23', '2024-08-12');
insert into user_group (company_name, start_date, end_date) values ('Jayo4103', '2021-08-21', '2024-02-06');
insert into user_group (company_name, start_date, end_date) values ('Jayo8385', '2021-09-06', '2024-04-24');
insert into user_group (company_name, start_date, end_date) values ('Brainverse5663', '2021-09-17', '2024-03-25');
insert into user_group (company_name, start_date, end_date) values ('Jaxworks8471', '2022-08-16', '2024-07-12');
insert into user_group (company_name, start_date, end_date) values ('Mynte8709', '2021-05-16', '2024-09-07');
insert into user_group (company_name, start_date, end_date) values ('Jabbertype87', '2021-07-31', '2024-05-27');
insert into user_group (company_name, start_date, end_date) values ('Ozu3379', '2021-05-27', '2024-10-24');
insert into user_group (company_name, start_date, end_date) values ('Brightbean4991', '2022-02-24', '2024-01-30');
insert into user_group (company_name, start_date, end_date) values ('Realmix8883', '2022-07-22', '2024-08-01');
insert into user_group (company_name, start_date, end_date) values ('Zoonoodle6684', '2021-10-12', '2024-07-23');
insert into user_group (company_name, start_date, end_date) values ('Brightdog7835', '2023-01-09', '2024-07-16');
insert into user_group (company_name, start_date, end_date) values ('Zoombox4529', '2022-06-11', '2024-03-24');
insert into user_group (company_name, start_date, end_date) values ('Jaloo5289', '2021-05-06', '2024-01-31');
insert into user_group (company_name, start_date, end_date) values ('Tagcat3712', '2022-11-02', '2024-05-22');
insert into user_group (company_name, start_date, end_date) values ('Dabshots3393', '2021-05-15', '2024-11-02');
insert into user_group (company_name, start_date, end_date) values ('Midel7928', '2022-11-03', '2024-07-27');
insert into user_group (company_name, start_date, end_date) values ('Eidel941', '2021-08-19', '2024-02-26');
insert into user_group (company_name, start_date, end_date) values ('Pixonyx2807', '2022-08-26', '2024-10-22');
insert into user_group (company_name, start_date, end_date) values ('Kwimbee4762', '2023-01-06', '2024-12-19');
insert into user_group (company_name, start_date, end_date) values ('Browsezoom3925', '2021-10-10', '2024-01-03');
insert into user_group (company_name, start_date, end_date) values ('Zava8917', '2022-08-21', '2024-10-11');
insert into user_group (company_name, start_date, end_date) values ('Zoozzy9504', '2022-09-12', '2024-07-11');
insert into user_group (company_name, start_date, end_date) values ('Divanoodle6139', '2022-01-04', '2024-02-19');
insert into user_group (company_name, start_date, end_date) values ('Ozu7255', '2022-10-15', '2024-07-06');
insert into user_group (company_name, start_date, end_date) values ('Jaxnation2140', '2021-09-09', '2024-05-06');
insert into user_group (company_name, start_date, end_date) values ('Dabvine6368', '2022-11-29', '2024-06-05');
insert into user_group (company_name, start_date, end_date) values ('Agivu4085', '2022-06-12', '2024-05-12');
insert into user_group (company_name, start_date, end_date) values ('Zooveo5491', '2021-12-11', '2024-04-10');
insert into user_group (company_name, start_date, end_date) values ('Ntags3313', '2022-05-14', '2024-07-30');
insert into user_group (company_name, start_date, end_date) values ('Npath6496', '2021-08-27', '2024-03-16');
insert into user_group (company_name, start_date, end_date) values ('Topiclounge2472', '2022-08-24', '2024-06-06');
insert into user_group (company_name, start_date, end_date) values ('Browsedrive4010', '2022-07-27', '2024-06-15');
insert into user_group (company_name, start_date, end_date) values ('Edgewire9951', '2022-06-03', '2024-03-10');
insert into user_group (company_name, start_date, end_date) values ('Skyvu8220', '2021-11-05', '2024-12-10');
insert into user_group (company_name, start_date, end_date) values ('Tavu310', '2022-06-08', '2024-06-22');
insert into user_group (company_name, start_date, end_date) values ('Tazz6755', '2022-12-05', '2024-10-28');
insert into user_group (company_name, start_date, end_date) values ('Bluejam6798', '2022-01-11', '2024-01-09');
insert into user_group (company_name, start_date, end_date) values ('Realcube4590', '2021-06-25', '2024-10-06');
insert into user_group (company_name, start_date, end_date) values ('Riffwire4489', '2021-07-29', '2024-04-11');
insert into user_group (company_name, start_date, end_date) values ('Oyoloo1580', '2022-12-30', '2024-12-24');
insert into user_group (company_name, start_date, end_date) values ('Thoughtstorm2305', '2022-10-30', '2024-07-27');
insert into user_group (company_name, start_date, end_date) values ('Voonyx3056', '2022-02-01', '2024-08-13');
insert into user_group (company_name, start_date, end_date) values ('Ooba4878', '2022-02-16', '2024-02-20');
insert into user_group (company_name, start_date, end_date) values ('Feedspan3045', '2021-12-07', '2024-11-03');
insert into user_group (company_name, start_date, end_date) values ('Babbleblab5483', '2022-11-11', '2024-12-13');
insert into user_group (company_name, start_date, end_date) values ('Avamba8721', '2021-08-02', '2024-03-10');
insert into user_group (company_name, start_date, end_date) values ('Voolia7738', '2022-07-07', '2024-05-18');
insert into user_group (company_name, start_date, end_date) values ('Dabshots815', '2022-04-08', '2024-05-16');
insert into user_group (company_name, start_date, end_date) values ('Jabbersphere3193', '2021-12-21', '2024-02-01');
insert into user_group (company_name, start_date, end_date) values ('Latz9134', '2022-02-27', '2024-11-21');
insert into user_group (company_name, start_date, end_date) values ('Linktype311', '2021-11-13', '2024-07-20');
insert into user_group (company_name, start_date, end_date) values ('Plajo647', '2022-10-12', '2024-05-07');
insert into user_group (company_name, start_date, end_date) values ('Tazzy1945', '2021-05-13', '2024-04-23');
insert into user_group (company_name, start_date, end_date) values ('Mycat9231', '2021-05-20', '2024-03-13');
insert into user_group (company_name, start_date, end_date) values ('Trupe4362', '2022-11-25', '2024-02-22');
insert into user_group (company_name, start_date, end_date) values ('Rhyzio6967', '2021-11-17', '2024-02-17');
insert into user_group (company_name, start_date, end_date) values ('Trupe7035', '2021-08-23', '2024-08-26');
insert into user_group (company_name, start_date, end_date) values ('Dabtype6890', '2021-12-30', '2024-07-27');
insert into user_group (company_name, start_date, end_date) values ('Demivee3222', '2022-01-10', '2024-06-06');
insert into user_group (company_name, start_date, end_date) values ('Yombu3618', '2021-05-26', '2024-01-05');
insert into user_group (company_name, start_date, end_date) values ('Browsebug9413', '2022-05-25', '2024-04-21');
insert into user_group (company_name, start_date, end_date) values ('Yambee774', '2021-11-14', '2024-12-16');
insert into user_group (company_name, start_date, end_date) values ('Vitz2181', '2022-12-13', '2024-08-29');
insert into user_group (company_name, start_date, end_date) values ('Dabshots42', '2021-05-07', '2024-07-22');
insert into user_group (company_name, start_date, end_date) values ('Tagchat8020', '2021-07-09', '2024-10-08');
insert into user_group (company_name, start_date, end_date) values ('Quire396', '2022-03-31', '2024-11-12');
insert into user_group (company_name, start_date, end_date) values ('Dabtype2605', '2022-03-09', '2024-12-04');
insert into user_group (company_name, start_date, end_date) values ('Dabjam2199', '2022-01-01', '2024-10-02');
insert into user_group (company_name, start_date, end_date) values ('Kimia8961', '2022-05-13', '2024-02-07');
insert into user_group (company_name, start_date, end_date) values ('Gigaclub2040', '2021-08-03', '2024-02-04');
insert into user_group (company_name, start_date, end_date) values ('Wordify8759', '2022-11-20', '2024-10-23');
insert into user_group (company_name, start_date, end_date) values ('Latz8142', '2022-05-09', '2024-09-28');
insert into user_group (company_name, start_date, end_date) values ('Oyondu5290', '2021-05-26', '2024-03-10');
insert into user_group (company_name, start_date, end_date) values ('Blognation9487', '2022-06-26', '2024-05-24');
insert into user_group (company_name, start_date, end_date) values ('Browsecat3575', '2022-02-11', '2024-11-08');
insert into user_group (company_name, start_date, end_date) values ('Demivee6672', '2021-10-30', '2024-04-30');
insert into user_group (company_name, start_date, end_date) values ('Blogpad5517', '2022-01-29', '2024-10-14');
insert into user_group (company_name, start_date, end_date) values ('Oyoba7614', '2022-07-07', '2024-06-20');
insert into user_group (company_name, start_date, end_date) values ('Kare2576', '2022-05-23', '2024-01-10');
insert into user_group (company_name, start_date, end_date) values ('Rhyloo4550', '2022-04-27', '2024-09-18');
insert into user_group (company_name, start_date, end_date) values ('Digitube5564', '2021-05-30', '2024-05-13');
insert into user_group (company_name, start_date, end_date) values ('Meeveo9574', '2022-09-25', '2024-08-02');
insert into user_group (company_name, start_date, end_date) values ('Jabberbean8981', '2021-07-22', '2024-04-22');
insert into user_group (company_name, start_date, end_date) values ('Topicblab7613', '2022-12-29', '2024-03-11');
insert into user_group (company_name, start_date, end_date) values ('Trupe2709', '2022-02-07', '2024-07-17');
insert into user_group (company_name, start_date, end_date) values ('Agimba104', '2021-11-18', '2024-06-08');
insert into user_group (company_name, start_date, end_date) values ('Latz8472', '2022-10-27', '2024-06-17');
insert into user_group (company_name, start_date, end_date) values ('Realpoint8100', '2021-10-03', '2024-06-11');
insert into user_group (company_name, start_date, end_date) values ('Babbleblab2164', '2022-09-01', '2024-09-29');
insert into user_group (company_name, start_date, end_date) values ('Oyondu8351', '2021-08-10', '2024-04-23');
insert into user_group (company_name, start_date, end_date) values ('Skyvu359', '2022-04-12', '2024-08-19');
insert into user_group (company_name, start_date, end_date) values ('Vinder4221', '2022-09-02', '2024-11-23');
insert into user_group (company_name, start_date, end_date) values ('Mynte951', '2022-01-11', '2024-04-28');
insert into user_group (company_name, start_date, end_date) values ('Devbug6735', '2022-08-31', '2024-02-02');
insert into user_group (company_name, start_date, end_date) values ('Babbleset2642', '2022-10-10', '2024-04-20');
insert into user_group (company_name, start_date, end_date) values ('Photobug5126', '2022-01-04', '2024-11-18');
insert into user_group (company_name, start_date, end_date) values ('Plambee6902', '2022-11-06', '2024-03-22');
insert into user_group (company_name, start_date, end_date) values ('Skipfire2832', '2022-08-17', '2024-12-16');
insert into user_group (company_name, start_date, end_date) values ('Leexo3468', '2021-09-26', '2024-01-29');
insert into user_group (company_name, start_date, end_date) values ('Twitternation7004', '2022-09-29', '2024-04-21');
insert into user_group (company_name, start_date, end_date) values ('Meedoo7806', '2021-05-12', '2024-07-01');
insert into user_group (company_name, start_date, end_date) values ('Yotz9294', '2022-07-07', '2024-04-04');
insert into user_group (company_name, start_date, end_date) values ('Skinix6374', '2021-06-27', '2024-03-11');
insert into user_group (company_name, start_date, end_date) values ('Abatz4816', '2022-02-25', '2024-11-18');
insert into user_group (company_name, start_date, end_date) values ('Eamia3558', '2022-05-11', '2024-02-20');
insert into user_group (company_name, start_date, end_date) values ('Minyx6909', '2022-07-19', '2024-03-31');
insert into user_group (company_name, start_date, end_date) values ('Eire2608', '2022-01-13', '2024-06-11');
insert into user_group (company_name, start_date, end_date) values ('Ozu3885', '2022-01-29', '2024-07-09');
insert into user_group (company_name, start_date, end_date) values ('Quimm4997', '2022-05-29', '2024-02-10');
insert into user_group (company_name, start_date, end_date) values ('Browsecat3235', '2022-09-18', '2024-11-29');
insert into user_group (company_name, start_date, end_date) values ('Quimm1903', '2021-08-21', '2024-11-13');
insert into user_group (company_name, start_date, end_date) values ('Twitterwire652', '2022-01-12', '2024-08-06');
insert into user_group (company_name, start_date, end_date) values ('Mycat598', '2021-07-08', '2024-06-16');
insert into user_group (company_name, start_date, end_date) values ('Yakijo5814', '2021-08-25', '2024-09-05');
insert into user_group (company_name, start_date, end_date) values ('Pixope7616', '2022-03-15', '2024-10-04');
insert into user_group (company_name, start_date, end_date) values ('Oyondu7736', '2021-11-29', '2024-04-28');
insert into user_group (company_name, start_date, end_date) values ('Realfire8740', '2022-08-13', '2024-04-07');
insert into user_group (company_name, start_date, end_date) values ('Kamba4851', '2022-10-16', '2024-07-14');
insert into user_group (company_name, start_date, end_date) values ('Thoughtstorm6475', '2021-12-08', '2024-04-22');
insert into user_group (company_name, start_date, end_date) values ('Digitube6638', '2022-08-07', '2024-06-21');
insert into user_group (company_name, start_date, end_date) values ('Livetube6931', '2021-12-12', '2024-06-02');
insert into user_group (company_name, start_date, end_date) values ('Topicware5390', '2021-08-11', '2024-09-04');
insert into user_group (company_name, start_date, end_date) values ('Voolith9549', '2022-03-16', '2024-03-02');
insert into user_group (company_name, start_date, end_date) values ('Dabshots1235', '2021-12-10', '2024-07-16');
insert into user_group (company_name, start_date, end_date) values ('Voonix7526', '2022-02-22', '2024-08-06');
insert into user_group (company_name, start_date, end_date) values ('Miboo6621', '2022-06-16', '2024-12-29');
insert into user_group (company_name, start_date, end_date) values ('Quinu621', '2022-12-29', '2024-07-08');
insert into user_group (company_name, start_date, end_date) values ('Skimia6982', '2021-06-13', '2024-04-14');
insert into user_group (company_name, start_date, end_date) values ('Tambee9453', '2021-09-12', '2024-07-24');
insert into user_group (company_name, start_date, end_date) values ('Kare6400', '2022-08-04', '2024-09-14');
insert into user_group (company_name, start_date, end_date) values ('Gabtune8777', '2021-10-04', '2024-04-03');
insert into user_group (company_name, start_date, end_date) values ('Jetwire9848', '2021-09-07', '2024-06-03');
insert into user_group (company_name, start_date, end_date) values ('Babbleopia2561', '2021-12-07', '2024-05-20');
insert into user_group (company_name, start_date, end_date) values ('Midel8892', '2021-11-22', '2024-05-22');
insert into user_group (company_name, start_date, end_date) values ('Mynte7560', '2022-12-26', '2024-01-06');
insert into user_group (company_name, start_date, end_date) values ('Podcat8368', '2022-06-23', '2024-07-21');
insert into user_group (company_name, start_date, end_date) values ('Topicblab7518', '2022-04-11', '2024-12-25');
insert into user_group (company_name, start_date, end_date) values ('Dabvine9361', '2022-11-04', '2024-08-10');
insert into user_group (company_name, start_date, end_date) values ('Oyoyo1381', '2021-05-13', '2024-01-02');
insert into user_group (company_name, start_date, end_date) values ('Abatz2444', '2022-05-17', '2024-06-28');
insert into user_group (company_name, start_date, end_date) values ('Eidel2430', '2022-05-23', '2024-10-04');
insert into user_group (company_name, start_date, end_date) values ('Skibox3435', '2022-12-26', '2024-08-19');
insert into user_group (company_name, start_date, end_date) values ('Cogibox9188', '2021-12-29', '2024-01-24');
insert into user_group (company_name, start_date, end_date) values ('Buzzbean655', '2021-06-26', '2024-01-17');
insert into user_group (company_name, start_date, end_date) values ('Blognation9813', '2022-07-26', '2024-06-18');
insert into user_group (company_name, start_date, end_date) values ('Dabjam9450', '2022-09-10', '2024-08-14');
insert into user_group (company_name, start_date, end_date) values ('Chatterbridge5267', '2022-05-06', '2024-11-30');
insert into user_group (company_name, start_date, end_date) values ('Thoughtstorm6634', '2022-12-24', '2024-02-23');
insert into user_group (company_name, start_date, end_date) values ('Centidel1192', '2021-08-22', '2024-05-05');
insert into user_group (company_name, start_date, end_date) values ('Yata2398', '2022-01-11', '2024-05-08');
insert into user_group (company_name, start_date, end_date) values ('Yadel5231', '2022-11-09', '2024-02-18');
insert into user_group (company_name, start_date, end_date) values ('Jetpulse2911', '2021-05-24', '2024-08-27');
insert into user_group (company_name, start_date, end_date) values ('Twiyo2119', '2022-03-30', '2024-04-30');
insert into user_group (company_name, start_date, end_date) values ('Cogidoo3042', '2022-07-21', '2024-02-24');
insert into user_group (company_name, start_date, end_date) values ('Aivee3654', '2022-02-28', '2024-09-25');
insert into user_group (company_name, start_date, end_date) values ('Voolith8218', '2022-11-11', '2024-07-10');
insert into user_group (company_name, start_date, end_date) values ('Linktype5976', '2022-03-29', '2024-03-02');
insert into user_group (company_name, start_date, end_date) values ('Flashpoint8941', '2022-08-10', '2024-05-02');
insert into user_group (company_name, start_date, end_date) values ('Topicshots8886', '2021-05-23', '2024-07-23');
insert into user_group (company_name, start_date, end_date) values ('Kazio114', '2021-10-24', '2024-06-09');
insert into user_group (company_name, start_date, end_date) values ('Eazzy9673', '2022-11-08', '2024-07-09');
insert into user_group (company_name, start_date, end_date) values ('Cogilith5111', '2022-04-15', '2024-07-01');
insert into user_group (company_name, start_date, end_date) values ('Realfire5484', '2021-10-31', '2024-05-22');
insert into user_group (company_name, start_date, end_date) values ('Tavu4840', '2021-09-11', '2024-10-13');
insert into user_group (company_name, start_date, end_date) values ('Jatri2027', '2022-03-14', '2024-09-05');
insert into user_group (company_name, start_date, end_date) values ('Tanoodle7455', '2021-11-06', '2024-07-21');
insert into user_group (company_name, start_date, end_date) values ('Tazzy8572', '2022-11-12', '2024-10-01');

# dummy users
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Angeli', 'qpTXcuibg', 'adakhno0@chronoengine.com', 'Chief Design Engineer', 11, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sara-ann', 'SegCupKF', 'sforre1@google.fr', 'Research Associate', 12, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Gilly', 'd17vXpVu3u', 'goris2@sciencedaily.com', 'Occupational Therapist', 13, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Vivi', 'cw9LDU9gHLM', 'vdart3@telegraph.co.uk', 'Safety Technician I', 14, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Shelly', '54AKNfXn3z', 'sdossettor4@blogspot.com', 'Actuary', 15, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Joshua', 'OuCCsrKci', 'jbraidley5@smh.com.au', 'Data Coordiator', 16, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ashil', 'k2oDDK7XVOhN', 'astanbury6@reuters.com', 'Research Nurse', 17, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Perice', 'xwSdWxn', 'pjealous7@upenn.edu', 'Environmental Tech', 18, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Dewey', '3fvQ6BKOhb', 'dwash8@163.com', 'Marketing Manager', 19, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Kleon', 'Rd3mJkvtdtR', 'kvandervlies9@about.me', 'Project Manager', 20, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Lonni', 'MzUOQlsYdPoI', 'lkingsnoada@bing.com', 'Geologist II', 21, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ilise', '4Eg7ML3P', 'idwireb@issuu.com', 'Structural Analysis Engineer', 22, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Judi', 'm8kYmt', 'jsilverstonec@addthis.com', 'Editor', 23, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Dona', 'qpXqpMeAv9SA', 'dgerholdd@123-reg.co.uk', 'Technical Writer', 24, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Demetria', 'Svp9V59LyF', 'dfarrare@phoca.cz', 'Senior Editor', 25, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sherye', 'Qpet2yl', 'sevreuxf@macromedia.com', 'Senior Cost Accountant', 26, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Wynnie', 'AvhyIGQj', 'wmowsdaleg@trellian.com', 'Legal Assistant', 27, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Laughton', 'ol1oMMcPaJ', 'laudash@eventbrite.com', 'Social Worker', 28, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Gawen', 'n7bGzsY8R0', 'gfurzeri@gmpg.org', 'Clinical Specialist', 29, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bald', 'swCxv2ztsz', 'bfaulconerj@census.gov', 'Research Nurse', 30, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Meridel', '1kiwVY', 'mmccrackenk@yolasite.com', 'Librarian', 31, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Melesa', '369Cqr', 'mspaicel@constantcontact.com', 'Legal Assistant', 32, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Arne', 'rfEGPzUmA', 'anewism@gizmodo.com', 'Technical Writer', 33, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Guillaume', 'umT2wVCSMoyQ', 'glambertinin@wired.com', 'Administrative Officer', 34, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Karel', 'TOtGyuc', 'kmarteleto@usatoday.com', 'Account Coordinator', 35, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Troy', 'HJyBQYVuLlc', 'tdedrickp@amazon.co.jp', 'Chemical Engineer', 36, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Diane', 'jzye9E', 'dangoveq@arstechnica.com', 'Structural Engineer', 37, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Lynnet', 'sqfmyPTY', 'lprogerr@wikipedia.org', 'Cost Accountant', 38, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Anet', 'w9D9iaWz', 'ajillitts@de.vu', 'Marketing Assistant', 39, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Anselma', 'Zj6dt0xQ', 'abartakt@engadget.com', 'Chief Design Engineer', 40, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Linell', '4a3x6YqZA', 'lsemonu@lulu.com', 'Analyst Programmer', 41, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Shell', 'rZFEqfG', 'srennoxv@pagesperso-orange.fr', 'Administrative Officer', 42, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bab', 'Lcfrfmnchjnd', 'bskainw@comsenz.com', 'Biostatistician II', 43, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Guilbert', 'cntNd0', 'gpogex@webmd.com', 'Registered Nurse', 44, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sapphire', 'JY0SPqPWdQdB', 'sorbelly@pbs.org', 'Speech Pathologist', 45, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Zeke', 'Ps1LOK0Aj9', 'zbessentz@xrea.com', 'Environmental Tech', 46, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Carlos', 'sjjrwpoTCHj', 'cbooty10@parallels.com', 'Environmental Specialist', 47, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Barnabe', 'BKbI0g2LlK', 'bohallihane11@scientificamerican.com', 'Senior Editor', 48, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Neron', 'ejGu8J', 'nbaytrop12@edublogs.org', 'Electrical Engineer', 49, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Reinhard', '1bXRhFi', 'rcianelli13@creativecommons.org', 'Computer Systems Analyst III', 50, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Lonna', 'WMBot6H2k', 'lfiggess14@wunderground.com', 'Environmental Tech', 51, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Estele', 'VhMLKK', 'emcgillecole15@wired.com', 'Clinical Specialist', 52, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Giffer', 'itthirQkO', 'gworvell16@surveymonkey.com', 'Assistant Manager', 53, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Lucinda', 'jwOPL31NVw0c', 'lwinser17@hatena.ne.jp', 'Financial Advisor', 54, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Annice', 'S3aw4u', 'awellstead18@geocities.jp', 'Food Chemist', 55, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Herve', 'TcPuwL', 'hcarragher19@mapquest.com', 'Account Coordinator', 56, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Clarisse', '29sBbLJzP2Z', 'callwood1a@cbslocal.com', 'GIS Technical Architect', 57, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Alessandra', 'K7aipqqPy', 'abrevetor1b@stumbleupon.com', 'Actuary', 58, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Hugh', 'P7ptapQJ', 'hdarch1c@privacy.gov.au', 'Recruiter', 59, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Cherri', '752M5Ia0Hn', 'ckissick1d@squidoo.com', 'Occupational Therapist', 60, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Saundra', 'Sn0CfGu9vdkY', 'scudmore1e@nih.gov', 'Civil Engineer', 61, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ashlie', 'F7wiXZ1prL', 'ajacobowitz1f@utexas.edu', 'Financial Analyst', 62, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Gavra', 'ygJ89Ka1MKhQ', 'gtessier1g@newyorker.com', 'Tax Accountant', 63, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Devland', 'oXZPFJunx6W', 'divons1h@arizona.edu', 'Nurse', 64, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Selene', '2Zj8yq2N', 'smunt1i@oakley.com', 'Recruiting Manager', 65, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Thorin', 's0HQXi', 'tdenisyev1j@admin.ch', 'Physical Therapy Assistant', 66, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Colleen', 'QTEzQdpr', 'cverbrugge1k@whitehouse.gov', 'Recruiter', 67, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Erika', 'NKDIKhGuc4', 'efaccini1l@free.fr', 'Design Engineer', 68, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Darlene', 'kYnWm6', 'dmcsaul1m@t-online.de', 'Automation Specialist II', 69, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Melessa', 'c0DjSa', 'mtelling1n@skype.com', 'Staff Scientist', 70, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Lenci', 'ckM26t0VQSKI', 'ltison1o@icio.us', 'Dental Hygienist', 71, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Gaile', 'EcVHpNrsxiHT', 'glavington1p@indiatimes.com', 'Data Coordiator', 72, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Deedee', 'Q792hk', 'dflear1q@last.fm', 'Graphic Designer', 73, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sioux', 'DBSfnIJW', 'shobble1r@prlog.org', 'Developer IV', 74, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sheffy', '1Vbhw5', 'sallwright1s@nba.com', 'Mechanical Systems Engineer', 75, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Eveleen', 'IN7IG8E3Qn', 'echarlin1t@privacy.gov.au', 'Structural Analysis Engineer', 76, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Allegra', 'EfBLiUhzFQhg', 'ascutter1u@ucsd.edu', 'Nuclear Power Engineer', 77, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Nanni', 'yHvKTRlu', 'nhuntar1v@walmart.com', 'Tax Accountant', 78, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Elvira', '8Wb44OFCojw', 'ealhirsi1w@washingtonpost.com', 'Actuary', 79, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Egan', 'qxGXWMCCcC', 'epicton1x@trellian.com', 'Senior Financial Analyst', 80, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Lexy', 'bcELmYqi9l', 'lrowbottam1y@forbes.com', 'Financial Advisor', 81, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Caresa', 'Ts0hb6', 'cburker1z@zimbio.com', 'VP Quality Control', 82, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Hadria', 'tKOUNzNJOH2B', 'hgumbley20@time.com', 'Pharmacist', 83, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Marne', 'K6AeUR6U', 'mgoodhand21@google.com.hk', 'Human Resources Manager', 84, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Vida', 'ephXEGm0ddK', 'vsighart22@xing.com', 'Tax Accountant', 85, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Edgard', 'NWhxuF1y', 'eends23@hp.com', 'VP Marketing', 86, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Antons', 'DdTqCjmmvTK6', 'acroneen24@1688.com', 'Help Desk Operator', 87, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Garreth', 'kUoVjZGWi', 'gbalbeck25@kickstarter.com', 'Analog Circuit Design manager', 88, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Saudra', 'NYYwvflS', 'scobelli26@1688.com', 'Health Coach III', 89, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ariella', '5cowoC', 'afallowes27@smh.com.au', 'Quality Engineer', 90, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Daveen', 'Shze1MeY5dT', 'dhave28@nyu.edu', 'Senior Sales Associate', 91, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Angelo', 'IE0uk11uhgjY', 'amellenby29@earthlink.net', 'Help Desk Operator', 92, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Wolfie', '4Vi0NiFLkN', 'wkuhnel2a@bbc.co.uk', 'Technical Writer', 93, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Joelynn', 'roDwZlF', 'jgartsyde2b@wp.com', 'Cost Accountant', 94, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Catlee', 'i4naqPzJbQ', 'ctanzig2c@ovh.net', 'Paralegal', 95, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Georgi', '3fRPNP', 'gextall2d@weebly.com', 'Research Assistant I', 96, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Del', 'iQPr31uDLTr', 'dsmewings2e@bandcamp.com', 'Pharmacist', 97, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bald', '96rl8Q', 'bhayman2f@trellian.com', 'Structural Engineer', 98, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Kikelia', 'irMFVRH', 'kargont2g@sohu.com', 'Nurse', 99, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Shelby', 'MGdCUYeYm5i', 'sconeau2h@bigcartel.com', 'Staff Accountant I', 100, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Nichole', 'Z800v4t7g5Eg', 'nhamfleet2i@hibu.com', 'Community Outreach Specialist', 101, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Roda', 'gKMNuulj8r7', 'rclemo2j@bbb.org', 'Legal Assistant', 102, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Hedda', 'pRqfH124', 'hscraney2k@cbslocal.com', 'Assistant Media Planner', 103, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Gasparo', 'DGngEt', 'gmaccorkell2l@google.co.jp', 'VP Sales', 104, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Lorena', '3LbTBxlQH', 'linstone2m@scribd.com', 'VP Accounting', 105, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Abbott', 'yzSDMvMSuXr', 'aricharson2n@guardian.co.uk', 'GIS Technical Architect', 106, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Shandee', '46WRmS', 'salbiston2o@instagram.com', 'Editor', 107, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Joanne', 'nIt97S2oYCX', 'jbandey2p@shinystat.com', 'Structural Engineer', 108, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Perkin', 'vWHg7veFMhQN', 'pshinfield2q@yahoo.co.jp', 'Compensation Analyst', 109, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Danell', 'djGrMqH', 'drenshaw2r@artisteer.com', 'VP Sales', 110, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Mose', '1hPAbNEz', 'mmapston2s@github.com', 'Account Coordinator', 111, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Christiano', 'eNPgRZ', 'ckernan2t@bbb.org', 'Financial Advisor', 112, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Roseann', '2V1IX1PWr', 'rriddall2u@hexun.com', 'Actuary', 113, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Rahel', '6Ev5pTgd6', 'rmccollum2v@dell.com', 'Web Developer II', 114, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Daphene', 'RYAXWDGr', 'dbecerro2w@youku.com', 'Clinical Specialist', 115, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Egbert', 's38ZZFF', 'emoorton2x@ted.com', 'Nurse', 116, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Parrnell', 'Hxwhn953Lg', 'pplak2y@webs.com', 'Account Representative II', 117, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Carita', 'okmc7gAgJ4', 'cpatridge2z@rambler.ru', 'Junior Executive', 118, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Boone', '1bXKWO6em', 'bhalegarth30@alibaba.com', 'Electrical Engineer', 119, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Annnora', 'J2KsKC', 'aruperto31@soundcloud.com', 'Safety Technician IV', 120, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Deny', 'PJUMhM', 'dhalpine32@tripod.com', 'Biostatistician IV', 121, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Alasdair', 'bec23AC35', 'adeares33@vistaprint.com', 'Operator', 122, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bonita', 'ZOeUDcI', 'bivashin34@networksolutions.com', 'Marketing Assistant', 123, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Editha', 'x9Guc8M', 'ehanby35@reverbnation.com', 'Quality Control Specialist', 124, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Obadias', 'ReGyfAzvY2', 'oburstowe36@jiathis.com', 'Office Assistant I', 125, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Hilarius', 'bE8wPnYsq', 'hhalston37@harvard.edu', 'Data Coordiator', 126, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Jandy', 'PaMCVuy8O', 'jshortt38@discovery.com', 'Analyst Programmer', 127, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Zebedee', '4MRDeuFQnl', 'zbiskupek39@princeton.edu', 'Systems Administrator III', 128, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ester', '0Z9OFph', 'ereuter3a@shinystat.com', 'Graphic Designer', 129, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Adelina', '8Ssfzb9Y4', 'ayong3b@yahoo.co.jp', 'Senior Sales Associate', 130, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ethelred', '3mE6J9MYGfTp', 'escintsbury3c@mediafire.com', 'Junior Executive', 131, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Rickey', 'rHW0F5PBpI3', 'rdutt3d@patch.com', 'Operator', 132, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Pepi', 'nWea2ax4', 'pfaiers3e@feedburner.com', 'Safety Technician IV', 133, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Artair', 'Icrrg5m2', 'ayewdale3f@zdnet.com', 'Automation Specialist I', 134, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Godiva', 'yEyd7kHl2E', 'gpallasch3g@utexas.edu', 'Quality Control Specialist', 135, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Jolee', 'wxG2zRPM0b', 'jkeilty3h@tuttocitta.it', 'Engineer IV', 136, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Tedd', 'Fe03kvV3', 'tchin3i@g.co', 'Administrative Assistant I', 137, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Gaylor', 'gfwULl9YE', 'gblew3j@flavors.me', 'Accounting Assistant II', 138, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Barby', 'a4XNNagiHzn', 'blawrence3k@reddit.com', 'Geologist IV', 139, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Stephan', 'W1eEycwjTSs', 'snesfield3l@dyndns.org', 'Marketing Assistant', 140, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bil', 'Vx0woYgVh', 'bcrevy3m@usa.gov', 'Media Manager IV', 141, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bertrando', '22yTPh2sXw6', 'bteliga3n@free.fr', 'Design Engineer', 142, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Fae', 'benhSV', 'ftwiname3o@google.de', 'Accountant I', 143, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sylas', 'MnSOvjt', 'saggus3p@mlb.com', 'Office Assistant II', 144, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Gawen', 'ScmC4Bh', 'glawrance3q@imdb.com', 'Developer IV', 145, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bancroft', 'cQA1Lm', 'bstudart3r@w3.org', 'VP Quality Control', 146, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Kaleb', 'CoRKBXG5Zqu', 'kfilipic3s@paginegialle.it', 'Civil Engineer', 147, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Timmy', 'Xi0IRcMzKo7', 'tvirgoe3t@about.com', 'Research Nurse', 148, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Lani', 'voORdL', 'lswatheridge3u@ow.ly', 'Internal Auditor', 149, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Dion', '04NKOoLDAW7W', 'dpuzey3v@time.com', 'Civil Engineer', 150, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sybyl', 'z3KYy1', 'spapes3w@admin.ch', 'Paralegal', 151, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Gratiana', 'FhjfSwh', 'gcroser3x@simplemachines.org', 'Help Desk Technician', 152, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Olag', 'D36Frcu', 'omckane3y@yahoo.com', 'Office Assistant I', 153, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Pattie', 'bnHvPCoQ', 'pmasseo3z@blogger.com', 'Operator', 154, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Tiffy', 'Zl57RTgeNLvF', 'tkirwood40@businessinsider.com', 'Senior Cost Accountant', 155, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Kaleb', 'tzPJ4G', 'khillen41@sphinn.com', 'Web Designer I', 156, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Gauthier', '2FQ0zS6D0', 'gsegrave42@artisteer.com', 'Nuclear Power Engineer', 157, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Graham', 'U43sRil', 'gbanham43@samsung.com', 'Administrative Officer', 158, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Heddie', 'eivAS70YXR4', 'holdridge44@histats.com', 'Biostatistician IV', 159, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Dorolice', 'ovBsuka', 'dohalligan45@amazon.co.uk', 'Tax Accountant', 160, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Herman', 'OkediP5', 'hkraft46@google.com.br', 'Structural Engineer', 161, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Salvatore', 'FfKr9xhEtUG5', 'sdewerk47@amazon.de', 'Technical Writer', 162, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Elysha', 'lYV1jt7ryOH', 'eburdas48@phoca.cz', 'Senior Cost Accountant', 163, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Terry', 'SV2lfyiSIf', 'tmunnings49@google.com.br', 'Web Developer III', 164, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Trisha', 'qKl23n3', 'turidge4a@tuttocitta.it', 'Web Developer I', 165, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ingeborg', 'Ccm25oZXGPA', 'igrimsdell4b@dagondesign.com', 'Desktop Support Technician', 166, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Mohandis', 'UxtdZVY', 'msirr4c@mtv.com', 'Assistant Professor', 167, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Fancy', 'fYUot63s788', 'farrow4d@home.pl', 'Programmer III', 168, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Carley', '6lJKFv', 'cownsworth4e@timesonline.co.uk', 'Nurse Practicioner', 169, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Martita', 'pJKxB5Jpc1n', 'msidebotton4f@dion.ne.jp', 'Office Assistant II', 170, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Margret', '4dyzVjcAwCo', 'msommerlin4g@moonfruit.com', 'Physical Therapy Assistant', 171, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Brenn', 'uIDC31hwqng', 'bwykey4h@spiegel.de', 'Mechanical Systems Engineer', 172, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Rana', 'uaCLsVzmxlEB', 'rporkiss4i@howstuffworks.com', 'Biostatistician IV', 173, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Nikki', 'qf6BvLdll', 'nstuffins4j@spiegel.de', 'Product Engineer', 174, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Margit', 'YAlTvi', 'mbotha4k@shop-pro.jp', 'Compensation Analyst', 175, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Nike', '79kTmtAH3', 'nbenediktovich4l@washingtonpost.com', 'Human Resources Manager', 176, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bettine', 'wgO3ua', 'bodrought4m@ibm.com', 'Associate Professor', 177, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Marje', 'dVGLfeU', 'mcooley4n@symantec.com', 'Account Coordinator', 178, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Solomon', 'LpTKzL', 'sblase4o@dell.com', 'Analyst Programmer', 179, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ursola', 'kslCIt', 'umccourtie4p@boston.com', 'Biostatistician I', 180, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Robina', 'fkRfJokn2', 'rweatherhead4q@mediafire.com', 'Cost Accountant', 181, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Nelia', 'ATpEP6yACGRj', 'nbilbery4r@independent.co.uk', 'Cost Accountant', 182, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bernice', 'OUQqUDEX3', 'bshanks4s@yolasite.com', 'Assistant Professor', 183, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Mitzi', 'DAUFqa', 'mmcramsey4t@behance.net', 'Administrative Assistant IV', 184, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sydel', 'Px52YjB', 'ssaffill4u@is.gd', 'Senior Financial Analyst', 185, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Tallie', 'pKfqxukCeEIr', 'theiton4v@purevolume.com', 'Senior Cost Accountant', 186, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Davey', 'iF9QvcKyjv', 'dkinvan4w@google.cn', 'Civil Engineer', 187, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Kimberli', 'QDMdUrtfMY', 'kdinsey4x@webs.com', 'Administrative Officer', 188, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Marcos', '6KZMIr', 'mpurdy4y@pen.io', 'Software Test Engineer II', 189, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Artie', 'AS1rLzk2VCE', 'arosewall4z@google.fr', 'Assistant Media Planner', 190, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Coral', 'txilLKX', 'ccaldecot50@networkadvertising.org', 'Business Systems Development Analyst', 191, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Haywood', '7Rmx90v', 'hfaye51@adobe.com', 'Quality Control Specialist', 192, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Boyd', 'r64xZ0pdx', 'bstanbra52@histats.com', 'Tax Accountant', 193, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Riobard', '9gFduAh0ws', 'rmcilory53@yolasite.com', 'General Manager', 194, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ad', 'mSRzwXhUH', 'agobeaux54@newyorker.com', 'Computer Systems Analyst III', 195, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Menard', '27HDgWD3', 'mgammidge55@e-recht24.de', 'Computer Systems Analyst IV', 196, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Rosemarie', 'wBHOjqSGeq', 'rbenedyktowicz56@twitpic.com', 'Senior Cost Accountant', 197, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sallee', '2u3a5L6Y9CuI', 'snaseby57@macromedia.com', 'Actuary', 198, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Xenos', 'MRmqdxix5t4', 'xgravestone58@woothemes.com', 'Professor', 199, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Wren', 'oqrpHxaCjzL', 'wnapier59@icq.com', 'Financial Advisor', 200, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Octavius', 'c0NfsBMWaRD', 'oholdin5a@dyndns.org', 'Database Administrator III', 201, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Trever', 'mlMVZcTRpr0w', 'tfreiburger5b@bravesites.com', 'Associate Professor', 202, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Carl', '35Y9UXfNc', 'cphilipsen5c@over-blog.com', 'Software Test Engineer II', 203, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Christoforo', 'CCpV8x6', 'csterre5d@google.it', 'Staff Accountant II', 204, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bob', 'gr9inx', 'bginner5e@godaddy.com', 'Assistant Manager', 205, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Jenifer', 'AsW0adZ', 'jsex5f@phpbb.com', 'Senior Quality Engineer', 206, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Vina', 'WONzQe', 'vpastor5g@ustream.tv', 'Environmental Tech', 207, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ginnie', 'EeslcYoD9k', 'gcocksedge5h@arstechnica.com', 'Developer III', 208, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Cliff', 'ohxwvaur5', 'crickardsson5i@wikispaces.com', 'Biostatistician III', 209, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Joelie', '9dI9yA16aO', 'jswatten5j@webmd.com', 'Recruiter', 210, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Giacomo', 'Lpzwfgs', 'gjacks5k@instagram.com', 'Business Systems Development Analyst', 211, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sholom', 'QxWN84xD8r', 'sgregan5l@privacy.gov.au', 'Quality Control Specialist', 212, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Mathew', 'SjLssqD', 'mfilshin5m@weebly.com', 'Programmer II', 213, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Lissi', 'Ep4ndBeu7', 'lcudworth5n@imdb.com', 'Media Manager III', 214, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Benjie', 'cHioFM', 'bemilien5o@google.it', 'Help Desk Technician', 215, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Adlai', 'EuXcUNMTD13', 'apheazey5p@gmpg.org', 'Software Consultant', 216, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Mignon', 'mrz6yCW', 'mmacallen5q@cloudflare.com', 'Research Associate', 217, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Christen', '1KDymBKwX6jx', 'cdemicoli5r@cdc.gov', 'Junior Executive', 218, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Danni', 'GJYGIF', 'dsherar5s@washingtonpost.com', 'Nurse Practicioner', 219, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bradford', 'dWl90IH7h', 'bclingoe5t@nationalgeographic.com', 'Accountant IV', 220, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Daryl', '3idciUF', 'dimpey5u@eventbrite.com', 'Assistant Manager', 221, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Meghan', 'D3MMXg0Eb1dZ', 'mboolsen5v@oracle.com', 'Analog Circuit Design manager', 222, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Vaughan', 'sOvMpZ20a', 'vwasbrough5w@japanpost.jp', 'Technical Writer', 223, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Debora', 'vCCr8P', 'dbezzant5x@t.co', 'Database Administrator I', 224, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Francoise', 'OsvNearTo7', 'frevel5y@latimes.com', 'Senior Cost Accountant', 225, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Susette', 'lxuIK0g1uB', 'saumerle5z@e-recht24.de', 'Analyst Programmer', 226, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Kristos', 'tJht7g7M4Gu', 'kthying60@baidu.com', 'Developer IV', 227, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Roderigo', 'Zarot5V9sX4u', 'rthaim61@apache.org', 'Media Manager I', 228, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Zedekiah', 'jZMvfmX', 'zellerman62@rakuten.co.jp', 'Nuclear Power Engineer', 229, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Shanta', '41mH6q', 'sgoodfield63@naver.com', 'Account Executive', 230, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sibel', 'fbL1Rhre5zYO', 'scosty64@clickbank.net', 'GIS Technical Architect', 231, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Shauna', 'cnZ2Ma1', 'soneligan65@networkadvertising.org', 'Community Outreach Specialist', 232, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Regina', '3UiuBf3vrHf', 'rsibbert66@admin.ch', 'Graphic Designer', 233, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Jase', 'ToE3fJ', 'jobeirne67@adobe.com', 'Occupational Therapist', 234, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Cecilius', 'YLBGWVaXIQKp', 'cclulow68@usa.gov', 'Pharmacist', 235, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Flora', 'hyuoq1OO6', 'fbiddell69@rambler.ru', 'Accountant IV', 236, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Daffie', 'eakzZz', 'dsantino6a@hud.gov', 'Occupational Therapist', 237, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ki', 'Kps2vt', 'ksongist6b@icq.com', 'Speech Pathologist', 238, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Gordie', 'Qfr8S2r', 'ghearl6c@dedecms.com', 'Senior Financial Analyst', 239, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Marley', 'nS3EgvnYH', 'mpaeckmeyer6d@amazon.co.jp', 'Accountant IV', 240, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Seamus', '38ANcM', 'smanuelli6e@china.com.cn', 'Compensation Analyst', 241, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Friederike', 'R2doOSqFvdd', 'ftill6f@indiatimes.com', 'Speech Pathologist', 242, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Che', 'HGKHiygJrOT8', 'cpawfoot6g@goodreads.com', 'Human Resources Manager', 243, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Carey', '2NTjoy', 'cdarridon6h@google.cn', 'Environmental Tech', 244, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Towny', 'PMelvP', 'tpendleberry6i@smh.com.au', 'Account Executive', 245, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Klemens', '36mrJwF', 'kstockney6j@hao123.com', 'Editor', 246, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Kelci', 'HLU5rpG6T7d', 'kdickenson6k@microsoft.com', 'Financial Advisor', 247, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sadie', '27529j', 'svanderweedenburg6l@ustream.tv', 'Design Engineer', 248, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sue', 'PWGz0t', 'sblakely6m@nature.com', 'Director of Sales', 249, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Audie', 'KlazYM7', 'abarajas6n@umich.edu', 'Senior Cost Accountant', 250, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Kip', 'GymgkT', 'ktardiff6o@prweb.com', 'Tax Accountant', 251, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Merell', 'wM6Sje0J4', 'mbucksey6p@pinterest.com', 'Graphic Designer', 252, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Natale', 'gKMORVO', 'nlinzey6q@purevolume.com', 'VP Marketing', 253, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Marget', 'CkEnytnux10', 'mdownse6r@bloomberg.com', 'Senior Cost Accountant', 254, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Jock', 'URmh9M8', 'jmcconway6s@t.co', 'Legal Assistant', 255, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Mal', 'bMMUdmFlo', 'meales6t@example.com', 'Automation Specialist IV', 256, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Rene', '3eivjQm7OiO', 'rboulton6u@elpais.com', 'Office Assistant II', 257, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Beret', 'DPUi91', 'bcarlill6v@themeforest.net', 'Nurse Practicioner', 258, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Elsy', 'tKWfsqDRV', 'emcginlay6w@sfgate.com', 'Registered Nurse', 259, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Grier', 'rW6WMJR7', 'gdownham6x@taobao.com', 'Computer Systems Analyst II', 260, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Frazer', 'R64wldKR', 'fdenizet6y@ucoz.ru', 'Environmental Tech', 261, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Annora', 'w5lUCl6E', 'ahenstridge6z@rediff.com', 'Nurse Practicioner', 262, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Alyosha', 'Cg3wqiJ', 'agenthner70@nsw.gov.au', 'VP Marketing', 263, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Carlita', 'YmU2fojdSiz', 'ctrorey71@eventbrite.com', 'Cost Accountant', 264, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Halette', '03aiOmU1', 'hlackner72@blogspot.com', 'VP Marketing', 265, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Viviana', 'uRifmG3Bc', 'veuels73@dyndns.org', 'Senior Editor', 266, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Arlyn', 's4f3T08sfa8', 'aatley74@t-online.de', 'Registered Nurse', 267, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Beverlie', 's42qpdzo3H', 'blohoar75@hugedomains.com', 'Senior Sales Associate', 268, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Giffy', '8JDMITThCiLG', 'gmacquire76@disqus.com', 'Legal Assistant', 269, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Stirling', 'RRkxB3Nbe0rO', 'sgalvan77@vistaprint.com', 'Database Administrator II', 270, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Meridith', 'ub74Gc', 'mwinton78@timesonline.co.uk', 'Chief Design Engineer', 271, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Dorice', 'PCWQQle3Z', 'dblinco79@skyrock.com', 'Safety Technician IV', 272, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bartolomeo', '9KeAnHo', 'bstonary7a@bluehost.com', 'VP Accounting', 273, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Irma', 'U99LfMrByjQd', 'ikeizman7b@artisteer.com', 'Structural Engineer', 274, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Edouard', '27pEipfna', 'eorthmann7c@so-net.ne.jp', 'VP Accounting', 275, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Nessi', 'q3UETWu7qh', 'nfarish7d@csmonitor.com', 'Sales Representative', 276, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Milly', '22SoE1V9b', 'mmalzard7e@about.com', 'Food Chemist', 277, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ignaz', 'o2G31YU1u', 'ispiby7f@google.com.au', 'Graphic Designer', 278, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Siouxie', '8bzLyWs', 'sbesant7g@ebay.co.uk', 'Editor', 279, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Alexis', 'htoer5XtzCzO', 'aheffernon7h@dion.ne.jp', 'Systems Administrator II', 280, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Arlana', 'QctDy8', 'acreak7i@sakura.ne.jp', 'VP Quality Control', 281, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Nappie', 'wnPhrD', 'nlikly7j@fema.gov', 'Senior Financial Analyst', 282, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Gustavus', 'WYpFbJjP7T', 'ggradon7k@blinklist.com', 'Budget/Accounting Analyst IV', 283, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Lanny', 'M9j63tVx', 'lclissold7l@youku.com', 'Mechanical Systems Engineer', 284, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Kellsie', 'fCxfhaoZDeC', 'kwardingley7m@seesaa.net', 'Database Administrator III', 285, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Raff', 'P7Iw9TFK0AG', 'rleal7n@blogs.com', 'Registered Nurse', 286, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Wilek', 't9abTALh', 'wgaudin7o@cdbaby.com', 'Human Resources Manager', 287, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Ari', '8DG8wOT', 'acours7p@marriott.com', 'Administrative Officer', 288, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Raff', 'eHuLTX', 'rhobden7q@wikimedia.org', 'Registered Nurse', 289, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Cyrill', 'fgMbeAQo39t', 'cshore7r@google.es', 'Tax Accountant', 290, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Peta', 'FgjuhTrM', 'phuckstepp7s@spiegel.de', 'Electrical Engineer', 291, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Alane', 'c1jWNIWkmB', 'amccloughlin7t@symantec.com', 'Software Engineer IV', 292, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Uriah', 'UXG75qA', 'ubenesevich7u@alexa.com', 'Developer III', 293, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Taryn', 'QewvTx9U', 'tkynett7v@deviantart.com', 'Staff Scientist', 294, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Caro', 'PbG613rrB4', 'cjodkowski7w@weather.com', 'Senior Developer', 295, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Aubrey', '3LAH3DP5w', 'arodnight7x@java.com', 'Chief Design Engineer', 296, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Bentlee', 'K72WjPAC', 'btyas7y@tiny.cc', 'Nuclear Power Engineer', 297, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Shayne', '6oxoMu', 'sfilkov7z@stanford.edu', 'VP Quality Control', 298, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sylvia', 'gZqpekB43fG', 'smckeaney80@un.org', 'Human Resources Manager', 299, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Towny', 'AHUeKmCA', 'tshave81@cbc.ca', 'Safety Technician IV', 300, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Sacha', 'EdeXwn', 'scowdray82@so-net.ne.jp', 'Software Consultant', 301, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Kahlil', 'PEkWNfbvIIKA', 'kbye83@huffingtonpost.com', 'Junior Executive', 302, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Toby', 'LjTjVIJ', 'tspurden84@amazon.de', 'Research Associate', 303, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Abrahan', 'tnBd9FWOn', 'aaleveque85@chron.com', 'Software Consultant', 304, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Alexandr', 'kgMPIcf6O', 'afuentez86@google.ru', 'Geological Engineer', 305, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Obidiah', 'RQx0a7QPHypt', 'osteger87@w3.org', 'Help Desk Operator', 306, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Case', 'xsDPPL', 'cthurgood88@salon.com', 'Electrical Engineer', 307, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Morena', 'ZuCvNtR', 'mmunsey89@answers.com', 'Quality Engineer', 308, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Elnar', 'ybH2LVwocd', 'ebenedicto8a@woothemes.com', 'Tax Accountant', 309, TRUE);
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('Curtis', 'b1g1VCgNByO', 'ctitman8b@baidu.com', 'Budget/Accounting Analyst IV', 310, TRUE);


#게시글 없는 입주 업체
insert into user_group (company_name, start_date, end_date) values ('Tesla', '2022-11-12', '2024-10-01');

# 게시글 없는 입주업체 tesla 대표 / password
insert into users (nickname, password, email, position_name, group_id, is_admin) values ('musk', '$2a$10$5I1.lLdikA3lJYvtbnGuRekCjyUSITH98v.VEyDUOCPNag5F1EfK6', 'musk@test.com', 'CEO', 311, TRUE);


-- migrate:down

