-- migrate:up
insert into replies (user_id, feed_id, comment, is_private) values (5, 28, 'eleifend', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 189, 'ut massa quis', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 77, 'cras mi pede', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 133, 'eget nunc donec quis orci', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 142, 'vitae', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 66, 'feugiat et eros', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 1, 'tempus vel pede morbi', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 61, 'aenean fermentum donec ut mauris', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 193, 'curabitur in libero ut massa', 1);
insert into replies (user_id, feed_id, comment, is_private) values (3, 25, 'odio', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 59, 'ipsum aliquam non mauris', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 127, 'interdum eu tincidunt', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 154, 'nam nulla integer pede justo', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 111, 'volutpat quam pede lobortis ligula', 1);
insert into replies (user_id, feed_id, comment, is_private) values (3, 35, 'interdum in ante vestibulum', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 92, 'ornare imperdiet', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 89, 'vulputate justo in blandit ultrices', 0);
insert into replies (user_id, feed_id, comment, is_private) values (3, 197, 'pede venenatis non sodales sed', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 10, 'ullamcorper purus', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 8, 'semper rutrum nulla nunc purus', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 163, 'est phasellus sit', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 152, 'tristique in tempus', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 84, 'nullam', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 187, 'posuere', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 32, 'sapien a', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 44, 'vestibulum ante ipsum', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 8, 'nunc', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 105, 'at feugiat non pretium', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 190, 'lacus curabitur at ipsum ac', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 95, 'vestibulum sit amet cursus id', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 105, 'nunc commodo placerat praesent blandit', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 105, 'eget semper rutrum nulla', 0);
insert into replies (user_id, feed_id, comment, is_private) values (3, 24, 'non velit nec', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 97, 'vivamus tortor', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 167, 'sapien urna pretium', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 104, 'tempus vivamus in', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 74, 'rhoncus', 0);
insert into replies (user_id, feed_id, comment, is_private) values (3, 32, 'enim', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 162, 'tristique', 1);
insert into replies (user_id, feed_id, comment, is_private) values (3, 117, 'posuere cubilia', 0);
insert into replies (user_id, feed_id, comment, is_private) values (3, 160, 'ut odio cras', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 121, 'suspendisse', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 39, 'at', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 146, 'et ultrices posuere cubilia curae', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 103, 'in lectus pellentesque at nulla', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 117, 'sagittis dui vel', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 69, 'sociis natoque penatibus', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 75, 'at feugiat', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 129, 'luctus nec molestie sed', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 147, 'nunc viverra dapibus', 1);
insert into replies (user_id, feed_id, comment, is_private) values (5, 10, 'ultrices enim lorem ipsum dolor', 1);
insert into replies (user_id, feed_id, comment, is_private) values (3, 22, 'elit proin interdum mauris non', 0);
insert into replies (user_id, feed_id, comment, is_private) values (3, 90, 'massa donec dapibus duis at', 1);
insert into replies (user_id, feed_id, comment, is_private) values (5, 28, 'lorem quisque ut erat curabitur', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 16, 'natoque penatibus et', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 198, 'rutrum at lorem', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 196, 'mauris morbi non lectus aliquam', 0);
insert into replies (user_id, feed_id, comment, is_private) values (3, 149, 'malesuada in imperdiet et', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 131, 'mauris eget massa', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 138, 'nisi nam ultrices', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 25, 'justo nec condimentum', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 117, 'consectetuer eget rutrum at', 1);
insert into replies (user_id, feed_id, comment, is_private) values (5, 107, 'sodales sed tincidunt eu', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 168, 'luctus et ultrices', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 133, 'varius nulla facilisi', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 117, 'sit amet', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 111, 'lorem quisque ut', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 33, 'leo', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 152, 'posuere cubilia curae nulla', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 62, 'sed', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 136, 'pretium quis lectus suspendisse', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 55, 'nec euismod scelerisque', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 9, 'suspendisse potenti', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 114, 'eu massa donec', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 115, 'neque sapien', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 144, 'sapien', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 198, 'aliquam sit amet', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 50, 'id turpis', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 1, 'cras', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 127, 'natoque penatibus', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 192, 'et', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 140, 'morbi non', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 35, 'convallis eget', 1);
insert into replies (user_id, feed_id, comment, is_private) values (3, 21, 'auctor sed tristique', 0);
insert into replies (user_id, feed_id, comment, is_private) values (3, 18, 'sed', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 11, 'eu massa', 0);
insert into replies (user_id, feed_id, comment, is_private) values (3, 176, 'odio', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 159, 'id nisl venenatis lacinia', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 4, 'erat vestibulum sed', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 10, 'sed nisl nunc rhoncus', 1);
insert into replies (user_id, feed_id, comment, is_private) values (3, 108, 'ultrices posuere cubilia', 1);
insert into replies (user_id, feed_id, comment, is_private) values (5, 32, 'magna ac consequat metus sapien', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 188, 'nulla suspendisse potenti', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 149, 'mus', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 115, 'erat curabitur gravida', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 35, 'in est risus auctor sed', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 142, 'ac nulla sed vel enim', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 152, 'vestibulum ante ipsum', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 121, 'lorem', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 13, 'turpis eget elit sodales', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 89, 'donec odio', 1);
insert into replies (user_id, feed_id, comment, is_private) values (3, 160, 'vulputate', 1);
insert into replies (user_id, feed_id, comment, is_private) values (5, 90, 'tortor sollicitudin mi sit', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 176, 'velit vivamus vel nulla', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 155, 'orci luctus et ultrices', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 176, 'nullam porttitor lacus at turpis', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 189, 'felis donec semper', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 183, 'pede', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 47, 'lacus morbi quis tortor id', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 36, 'tortor quis turpis sed ante', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 92, 'cubilia curae donec pharetra', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 24, 'et ultrices posuere', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 63, 'posuere', 1);
insert into replies (user_id, feed_id, comment, is_private) values (5, 66, 'pellentesque', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 189, 'tortor', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 108, 'cursus urna ut tellus nulla', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 178, 'augue a', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 141, 'elementum', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 53, 'a suscipit nulla', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 1, 'augue aliquam', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 183, 'aliquam convallis nunc', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 110, 'sit amet sem fusce', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 187, 'elementum in hac habitasse', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 81, 'ante', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 135, 'elit proin risus praesent lectus', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 136, 'consequat dui nec', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 151, 'orci eget orci', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 47, 'in faucibus orci luctus et', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 120, 'felis ut at', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 167, 'consequat morbi a ipsum integer', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 187, 'nisl duis bibendum', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 185, 'sollicitudin', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 1, 'ut', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 179, 'neque libero convallis eget eleifend', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 118, 'vehicula consequat morbi a', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 31, 'pede libero quis', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 11, 'sapien a libero', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 145, 'tempus vivamus in felis', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 126, 'vel est', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 129, 'mi in porttitor', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 163, 'viverra dapibus', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 97, 'hac habitasse platea dictumst', 1);
insert into replies (user_id, feed_id, comment, is_private) values (5, 59, 'consequat dui nec', 1);
insert into replies (user_id, feed_id, comment, is_private) values (5, 19, 'sit amet cursus', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 59, 'quis orci nullam molestie', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 53, 'nec dui', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 163, 'ultrices posuere cubilia curae', 0);
insert into replies (user_id, feed_id, comment, is_private) values (3, 30, 'a libero nam dui', 1);
insert into replies (user_id, feed_id, comment, is_private) values (3, 112, 'a ipsum integer a nibh', 1);
insert into replies (user_id, feed_id, comment, is_private) values (5, 100, 'cubilia', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 110, 'in', 1);
insert into replies (user_id, feed_id, comment, is_private) values (3, 80, 'in', 0);
insert into replies (user_id, feed_id, comment, is_private) values (3, 1, 'donec dapibus', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 116, 'phasellus', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 186, 'accumsan odio curabitur convallis', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 47, 'pellentesque at', 1);
insert into replies (user_id, feed_id, comment, is_private) values (3, 131, 'eleifend luctus ultricies', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 82, 'nunc purus phasellus', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 12, 'mollis molestie lorem', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 8, 'tortor eu pede', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 44, 'quis lectus suspendisse potenti', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 97, 'suspendisse ornare consequat lectus in', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 159, 'sapien', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 88, 'in congue etiam justo etiam', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 185, 'consectetuer adipiscing elit proin', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 97, 'sodales sed tincidunt eu felis', 1);
insert into replies (user_id, feed_id, comment, is_private) values (3, 45, 'curae duis faucibus accumsan', 1);
insert into replies (user_id, feed_id, comment, is_private) values (3, 174, 'ut ultrices vel augue', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 29, 'ut mauris', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 175, 'faucibus', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 181, 'quam', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 3, 'nunc viverra dapibus nulla suscipit', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 112, 'laoreet ut rhoncus aliquet pulvinar', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 90, 'fusce consequat nulla nisl nunc', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 155, 'pede', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 74, 'ante', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 120, 'morbi ut odio cras', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 90, 'luctus', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 147, 'turpis', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 64, 'libero ut massa volutpat convallis', 0);
insert into replies (user_id, feed_id, comment, is_private) values (3, 161, 'lacus at turpis donec posuere', 1);
insert into replies (user_id, feed_id, comment, is_private) values (5, 174, 'quis turpis sed ante', 0);
insert into replies (user_id, feed_id, comment, is_private) values (4, 116, 'diam nam', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 99, 'magna bibendum imperdiet nullam orci', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 163, 'eleifend pede libero', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 154, 'curae donec pharetra magna', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 196, 'ac', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 11, 'enim leo rhoncus', 0);
insert into replies (user_id, feed_id, comment, is_private) values (6, 120, 'sapien cum', 0);
insert into replies (user_id, feed_id, comment, is_private) values (3, 74, 'sit', 1);
insert into replies (user_id, feed_id, comment, is_private) values (4, 18, 'euismod scelerisque', 1);
insert into replies (user_id, feed_id, comment, is_private) values (6, 38, 'tincidunt nulla mollis molestie', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 142, 'nulla neque', 1);
insert into replies (user_id, feed_id, comment, is_private) values (1, 52, 'ullamcorper', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 96, 'mi sit amet', 0);
insert into replies (user_id, feed_id, comment, is_private) values (1, 136, 'id turpis integer aliquet', 0);
insert into replies (user_id, feed_id, comment, is_private) values (2, 95, 'justo sollicitudin ut', 1);
insert into replies (user_id, feed_id, comment, is_private) values (2, 165, 'eget', 1);
insert into replies (user_id, feed_id, comment, is_private) values (5, 116, 'tortor', 0);
insert into replies (user_id, feed_id, comment, is_private) values (5, 102, 'amet nunc', 1);

#reply mockdata
insert into replies (user_id, feed_id, comment, parent_reply_id, is_private) values (1, 1, 'aliquam sit amet',7,  0);
insert into replies (user_id, feed_id, comment, parent_reply_id, is_private) values (4, 1, 'id turpis',79, 1);
insert into replies (user_id, feed_id, comment, parent_reply_id, is_private) values (6, 1, 'cras',120, 0);
insert into replies (user_id, feed_id, comment, parent_reply_id, is_private) values (1, 1, 'natoque penatibus',133, 1);
insert into replies (user_id, feed_id, comment, parent_reply_id, is_private) values (6, 1, 'ac', 7, 1);
insert into replies (user_id, feed_id, comment, parent_reply_id, is_private) values (6, 1, 'enim leo rhoncus', 7, 0);
insert into replies (user_id, feed_id, comment, parent_reply_id, is_private) values (6, 1, 'sapien cum', 7,1);

-- migrate:down

